In [1]:
!pip install neo4j

Requirement already satisfied: neo4j in /Users/jacobsimonsen/opt/anaconda3/lib/python3.9/site-packages (4.4.2)
Requirement already satisfied: pytz in /Users/jacobsimonsen/opt/anaconda3/lib/python3.9/site-packages (from neo4j) (2021.3)

In [3]:
from neo4j import GraphDatabase
import pandas as pd

In [8]:
url = 'https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawEventsData.csv'
sports = pd.read_csv(url, delimiter =',')
sports.head(20)

,Team,Type,Subtype,Period,Start Frame,Start Time [s],End Frame,End Time [s],From,To,Start X,Start Y,End X,End Y
0,Away,SET PIECE,KICK OFF,1,1,0.04,0,0.00,Player19,NaN,NaN,NaN,NaN,NaN
1,Away,PASS,NaN,1,1,0.04,3,0.12,Player19,Player21,0.45,0.39,0.55,0.43
2,Away,PASS,NaN,1,3,0.12,17,0.68,Player21,Player15,0.55,0.43,0.58,0.21
3,Away,PASS,NaN,1,45,1.80,61,2.44,Player15,Player19,0.55,0.19,0.45,0.31
4,Away,PASS,NaN,1,77,3.08,96,3.84,Player19,Player21,0.45,0.32,0.49,0.47
5,Away,PASS,NaN,1,191,7.64,217,8.68,Player21,Player22,0.40,0.73,0.32,0.98
6,Away,PASS,NaN,1,279,11.16,303,12.12,Player22,Player17,0.39,0.96,0.49,0.98
7,Away,BALL LOST,INTERCEPTION,1,346,13.84,380,15.20,Player17,NaN,0.51,0.97,0.27,0.75
8,Home,RECOVERY,INTERCEPTION,1,378,15.12,378,15.12,Player2,NaN,0.27,0.78,NaN,NaN
9,Home,BALL LOST,INTERCEPTION,1,378,15.12,452,18.08,Player2,NaN,0.27,0.78,0.59,0.64
10,Away,RECOVERY,INTERCEPTION,1,453,18.12,453,18.12,Player16,NaN,0.57,0.67,NaN,NaN
11,Away,BALL LOST,HEAD-INTERCEPTION,1,453,18.12,497,19.88,Player16,NaN,0.57,0.67,0.33,0.65
12,Away,CHALLENGE,AERIAL-LOST,1,497,19.88,497,19.88,Player18,NaN,0.38,0.67,NaN,NaN
13,Home,CHALLENGE,AERIAL-WON,1,498,19.92,498,19.92,Player2,NaN,0.36,0.67,NaN,NaN
14,Home,RECOVERY,INTERCEPTION,1,498,19.92,498,19.92,Player2,NaN,0.36,0.67,NaN,NaN
15,Home,PASS,HEAD,1,498,19.92,536,21.44,Player2,Player9,0.36,0.67,0.53,0.59
16,Home,PASS,NaN,1,536,21.44,556,22.24,Player9,Player10,0.53,0.59,0.50,0.65
17,Home,BALL LOST,INTERCEPTION,1,572,22.88,616,24.64,Player10,NaN,0.50,0.65,0.67,0.44
18,Away,RECOVERY,INTERCEPTION,1,618,24.72,618,24.72,Player16,NaN,0.64,0.46,NaN,NaN
19,Away,PASS,NaN,1,763,30.52,784,31.36,Player16,Player19,0.58,0.27,0.51,0.33

In [25]:
query_string = '''
    USING PERIODIC COMMIT 500
    LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawEventsData.csv"
    AS line FIELDTERMINATOR ','
    CREATE (:Sport {team: line.Team, passes: line.Type, from_player: line.From, to_player: line.To}) 
    '''

In [26]:
  # Create a connection class
class Neo4jConnection:
    
    def __init__(self, uri, user, pwd):
        self.__uri = uri
        self.__user = user
        self.__pwd = pwd
        self.__driver = None
        try:
            self.__driver = GraphDatabase.driver(self.__uri, auth=(self.__user, self.__pwd))
        except Exception as e:
            print("Failed to create the driver:", e)      
        
    def query(self, query, db=None):
        assert self.__driver is not None, "Driver not initialized!"
        session = None
        response = None
        try: 
            session = self.__driver.session(database=db) if db is not None else self.__driver.session() 
            response = list(session.run(query))
        except Exception as e:
            print("Query failed:", e)
        finally: 
            if session is not None:
                session.close()
        return response
    
    def close(self):
        if self.__driver is not None:
            self.__driver.close()

In [27]:
conn = Neo4jConnection(uri="bolt://localhost:7687", user="neo4j", pwd="1234")

In [28]:
conn.query("CREATE OR REPLACE DATABASE neo4j")

[]

In [29]:
conn.query(query_string, db='neo4j')

[]

In [49]:
query_string = '''
WITH https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawEventsData.csv AS rels
LOAD CSV WITH HEADERS FROM rels AS row MATCH (:Sport {id: line.From})
MATCH (:Sport {id: line.To})
MERGE (origin)-[:EROAD {distance: toInteger(row.cost)}]->(destination)
    '''

In [57]:
query_string = '''
LOAD CSV WITH HEADERS FROM 'https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawEventsData.csv'
AS line FIELDTERMINATOR ','
MATCH (from_p:Place {id: line.From})
MATCH (to_p:Place {id: line.To})
MERGE (from_p)-[:Type]->(to_p)
    '''

In [58]:
conn.query(query_string, db='neo4j')

[]